spring:
  mail:
    host: smtp.qq.com
    username: xxx@qq.com
    ## not password
    password: xxx
    default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 512000 #文件大小最大 500kb
      max-request-size:  512000 #文件大小最大 500kb
  cache.type: redis
#  测试区host
  #redis.host:
  redis.host: 127.0.0.1
  redis.port: 6379
  redis.lettuce.pool.max-active: 500
  redis.lettuce.pool.max-idle: 300
  redis.lettuce.pool.min-idle: 10
  redis.lettuce.pool.max-wait: 1000ms
  redis.lettuce.shutdown-timeout: 500000ms
  datasource:
    platform: mysql
    initialization-mode: always
    druid:
#      测试环境
      url:  jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      driver-class-name:  com.mysql.cj.jdbc.Driver
      username:  root
      password:  root
      initial-size:  10
      max-active:  50
      min-idle:  10
      max-wait:  60000
      pool-prepared-statements:  true
      max-pool-prepared-statement-per-connection-size:  20
      validation-query:  SELECT 1 FROM DUAL
      test-on-borrow:  false
      test-on-return:  false
      test-while-idle:  true
      time-between-eviction-runs-millis:  60000
      filters:  stat,wall
  jpa:
    show-sql: true

mybatis:
  mapper-locations: "classpath:mapper/*.xml"
  type-aliases-package: com.caili.pojo
  configuration:
   map-underscore-to-camel-case: true
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: pages=countSql
#开启mybatis的sql日志打印
#logging.level.com.wisesystem.litemall.db.dao: trace


qq:
  oauth:
    http:
    #//QQ互联中填写的网站地

constants:
    QQ:
    qqAppId: 12209
   qqAppSecret: 12209
   qqRedirectUrl: 12209
   WECHAT:
   weChatAppId: 12209
   weChatAppSecret: 12209
   weChatRedirectUrl: 12209
server:
  port: 8080
